project_id = "nexzfjqsdxptpxpsrbkz"

[functions.chat-api]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.send-cheatsheet]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.quran-word-lookup]
verify_jwt = false

[functions.arabic-word-analysis]
verify_jwt = false